import type { Metadata, NextPage } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const runtime = 'edge';

type Props = {
  children: ReactNode;
};

const Layout: NextPage<Props> = ({ children }) => {
  return (
    <html lang='ja'>
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default Layout;
